### ISSUE TITLE
Snowboy abandoned?

### ISSUE THREAD

**Issue by edurenye** [rhasspy/wyoming-snowboy#1]
This is more a question than an issue.

Wasn't this project abandoned on 21st of December 2020 acording to the https://github.com/Kitt-AI/snowboy readme file?
Does it make sense to support an abandoned project? Or are you using some fork that is being maintained?

**Comment by synesthesiam** [comment]
Snowboy is abandoned, but still works just fine. The [snowman](https://github.com/Thalhammer/snowman/) project has reverse engineered both the detector and the wake word training. I'm using the original detector, but snowman's wake word training process.
